"""Render the documentation sheet for the derived simplified glyphs.

The pictures in ``docs/simplified-extension.md`` are the only place the derived
shapes can be reviewed without installing the font, so they are generated by a
script rather than by hand, straight from the finished faces:

* every weight gets one row of the characters ``tools/extend_font.py`` derived
  for it (rule-derived and borrowed alike);
* a second sheet shows where each column comes from -- drawn by Zen Maru itself,
  recomposed from the face's own contours, or borrowed from the pinned reference
  -- so the borrowed weight can be compared with the native one at a glance.

Usage::

    python3 tools/make_extension_sheet.py [--faces build/fonts-simplified]
"""
from __future__ import annotations

import argparse
from pathlib import Path

import freetype
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
CHARACTERS = "贝页见马鸟乌岛飞门员维陈东护进迁赵"
NATIVE = "体永国字"        # drawn by Zen Maru itself
RECIPE_DERIVED = "贝马鸟门护东"  # recomposed from the face's own contours
BORROWED = "偿叠橥恿巅摹"   # imported from the pinned reference font
FACES = ("Light", "Regular", "Medium", "Bold", "Black")
SIZE = 130
LINE = 26


def render(path: Path, characters: str, label: str) -> Image.Image:
    """One row of characters, drawn straight from the face with FreeType."""
    face = freetype.Face(str(path))
    face.set_char_size(SIZE * 64)
    step = int(SIZE * 1.08)
    sheet = Image.new("L", (len(characters) * step + 24, SIZE + LINE + 34), 255)
    draw = ImageDraw.Draw(sheet)
    draw.text((10, 8), label, fill=0)
    x = 12
    for char in characters:
        face.load_char(char, freetype.FT_LOAD_RENDER)
        bitmap = face.glyph.bitmap
        if bitmap.rows and bitmap.width:
            ink = Image.frombytes("L", (bitmap.width, bitmap.rows), bytes(bitmap.buffer))
            sheet.paste(0, (x + face.glyph.bitmap_left, LINE + 12 + SIZE - face.glyph.bitmap_top), ink)
        x += step
    return sheet


def missing(face_path: Path, characters: str) -> list[str]:
    from fontTools.ttLib import TTFont

    cmap = TTFont(face_path, lazy=True).getBestCmap()
    return [char for char in characters if ord(char) not in cmap]


def build(faces: Path, output: Path) -> Path:
    rows = []
    for style in FACES:
        path = faces / f"SelffontMaru-{style}.ttf"
        absent = missing(path, CHARACTERS)
        label = f"Selffont Maru {style}"
        if absent:
            label += f"  （没有：{' '.join(absent)}——该字重无法派生，回退系统字体）"
        rows.append(render(path, "".join(c for c in CHARACTERS if c not in absent), label))
    width = max(row.width for row in rows)
    height = sum(row.height + 8 for row in rows)
    sheet = Image.new("L", (width, height), 240)
    y = 0
    for row in rows:
        sheet.paste(row, (0, y))
        y += row.height + 8
    output.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(output)
    return output


def build_reference_sheet(faces: Path, output: Path) -> Path:
    """Three-way sheet: native, rule-derived and borrowed, weight by weight."""
    rows, gap = [], 10
    for style in FACES:
        row = render(faces / f"SelffontMaru-{style}.ttf", NATIVE + RECIPE_DERIVED + BORROWED, style)
        rows.append(row)
    width = max(row.width for row in rows)
    height = sum(row.height + gap for row in rows)
    sheet = Image.new("L", (width, height), 240)
    draw_y = 0
    for row in rows:
        sheet.paste(row, (0, draw_y))
        draw_y += row.height + gap
    draw = ImageDraw.Draw(sheet)
    step = int(SIZE * 1.08)
    for boundary in (len(NATIVE), len(NATIVE) + len(RECIPE_DERIVED)):
        x = 12 + boundary * step - step // 3
        draw.line([(x, 0), (x, sheet.height)], fill=170, width=3)
    output.parent.mkdir(parents=True, exist_ok=True)
    sheet.save(output)
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--faces", type=Path, default=ROOT / "build/fonts-simplified")
    parser.add_argument("--output", type=Path,
                        default=ROOT / "docs/images/simplified-extension.png")
    parser.add_argument("--reference-output", type=Path,
                        default=ROOT / "docs/images/reference-borrowing.png")
    args = parser.parse_args()
    print(build(args.faces, args.output))
    print(build_reference_sheet(args.faces, args.reference_output))


if __name__ == "__main__":
    main()
